### ISSUE TITLE
화면 디자인 관련 -> 조연주

### ISSUE THREAD

**Issue by ChunSamKim** [M00NPANG/SenierProject_O.O#10]
1. 처음 회원가입 진행할 때 아이디, 닉네임, 비밀번호 다 확인한 후,  퍼스널 컬러 측정을 위한 사진을 찍거나 갤러리를 열 때 쓸 액티비티의 화면 구성, 키랑 몸무게는 안받아도 됨

2. 1의 작업 후 사진을 서버로 보내고, 그 결과로 퍼스널컬러를 받은 후 사용자에게 퍼스널컬러가 무엇인지 보여줄 때를 위한 액티비티의 화면 구성

3. 로그인 액티비티에서 "비밀번호를 잊으셨나요?"를 누르면 쓸 액티비티의 화면 구성

4. 날씨 표현을 위한 이미지가 낮을 표현하는 태양밖에 없음. 밤 시간대에  sun 대신 쓸 moon,  little_cloud 대신 쓸 little_cloud_moon 이미지를 제작

이상 1~4까지 해서 보내주셈

**Comment by Yeonju02** [comment]
일요일까지 완성해서 보내줄게
