### ISSUE TITLE
서버 -> 프런트 : 회원 관리 모듈 관련 알림

### ISSUE THREAD

**Issue by M00NPANG** [M00NPANG/SenierProject_O.O#2]
사용자 선호 색  양식
red , orange, yellow, green, blue, purple, brown, gray

사용자 선호 스타일 양식
strete, modern, minimal, feminine, simpleBasic, americanCasual, businessCasual, casual, retro, sports, classic, elegant, girlish, tomboy, vintage

**Comment by M00NPANG** [comment]
아이디 중복 확인 기능은 완료했어용.

회원가입 관련 입출력은

Input

POST http://localhost:8080/api/join
Content-Type: application/json

{
  "password": "",
  "email": "",
  "name": "",
  "user_percol": "r",
  "user_color": "",
  "user_style": ""
}

Output

이메일 중복 있음 : “이미 사용 중인 이메일입니다. 다른 이메일을 입력해주세요.” 
이메일 중복 없음 : 받아온 이메일  return

**Comment by ChunSamKim** [comment]
퍼스널컬러  각 값들 알려줘
