### ISSUE TITLE
서버 기능확인 바람

### ISSUE THREAD

**Issue by ChunSamKim** [M00NPANG/SenierProject_O.O#3]
이메일, 닉네임 중복유무 확인해서 결과를 프론트로 보내주세요

각 결과에 따른 반환값 알려주세요

**Comment by M00NPANG** [comment]
- 이메일 중복시 "이미 사용 중인 이메일입니다. 다른 이메일을 입력해주세요." 문자열 전송.
- 닉네임 중복시 "이미 사용중인 닉네임입니다. 다른 닉네임을 입력해주세요." 문자열 전송.

회원가입 api/join으로 http 요청을 할 때 마다 확인을 하게 됩니다. 다른 반환값으로 변경 원하시면 알려주세용
