### ISSUE TITLE
데이터베이스 관련

### ISSUE THREAD

**Issue by ChunSamKim** [M00NPANG/SenierProject_O.O#9]
개별 옷 아이템 전용 테이블과 코디세트용 테이블을 따로 두어야 할 것 같음

현재 image 테이블 구조는 img_id, file_name, file_ori_name, file_url인데

코디세트는 일단 필요한게 1. 코디세트id, 2. 제작자닉네임, 3. 사용자프로필사진,  4. 좋아요 수, 5. 코디세트 이미지, 6. 코디이름, 7. 태그, 8. 구독여부, 9. 주요 색감.   <- 이정도가 필요함

그리고 구독 기능을 위한 구독자/피구독자  전용 중간 테이블도 필요함

옷 아이템용, 코디세트용, 구독자/피구독자용 테이블을 만드는게 어떤가?

**Comment by M00NPANG** [comment]
ㅇㅋ 확인이용. 개선되면 알려드릴게요.

**Comment by M00NPANG** [comment]
구독은 일단 다른 DB 테이블로 다룰거라서 지금은 기능에서 제외해주세용. 사용자 이미지와 구독 여부를 다른 방식으로 가져오는게 좋을 것 같아서 게시물은 프론트에서 보내주실 때  << 닉네임,  코디세트 이미지, 코디 이름, 태그, 주요 색감>> 요 정도 일 것 같습니다. 보내드릴 때에는 제가 따로 정리해서 이슈를 올리도록 하겠습니당.
